import { ROUTES } from '../routes/paths.js';

const module = (role, eyebrow, title, icon, description, metrics, steps, links) => ({ role, eyebrow, title, icon, description, metrics, steps, links });

export const productModules = {
  candidateProfile: module('candidate', 'Digital talent identity', 'Your verified professional signal.', 'fingerprint',
    'Connect the work you are proud of, then turn it into a single evidence-led profile that recruiters can trust.',
    [['Evidence sources', '06'], ['Verified skills', '24'], ['Profile strength', '92%']],
    ['Connect GitHub, portfolio, credentials, and achievements.', 'Review the evidence attached to every skill.', 'Share one trusted talent identity with employers.'],
    [['Open talent cockpit', ROUTES.CANDIDATE_OVERVIEW, 'space_dashboard'], ['Practice interview', ROUTES.INTERVIEW, 'record_voice_over'], ['View career roadmap', ROUTES.CANDIDATE_ROADMAP, 'route']]),
  candidateRoadmap: module('candidate', 'Career intelligence', 'A clearer next move for your career.', 'route',
    'Prioritise the skills, projects, and proof points that will make the greatest difference to your next opportunity.',
    [['Growth opportunities', '03'], ['Current trajectory', 'Strong'], ['Next review', '30 days']],
    ['Strengthen system-design evidence with one deployed case study.', 'Document architecture choices in your most active repository.', 'Complete a practice interview and add the verified outcome to your profile.'],
    [['Open talent cockpit', ROUTES.CANDIDATE_OVERVIEW, 'space_dashboard'], ['Build your identity', ROUTES.CANDIDATE_PROFILE, 'fingerprint'], ['Practice interview', ROUTES.INTERVIEW, 'record_voice_over']]),
  recruiterPipeline: module('recruiter', 'Hiring workspace', 'Move qualified talent forward with confidence.', 'account_tree',
    'Keep every shortlist, evidence review, and candidate decision in one focused hiring workspace.',
    [['Active candidates', '18'], ['Evidence reviewed', '12'], ['Ready to interview', '05']],
    ['Review the candidates surfaced by Talent Search.', 'Open the evidence behind every score before a decision.', 'Move finalists into an interview-ready shortlist.'],
    [['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['Compare candidates', ROUTES.RECRUITER_COMPARE, 'compare_arrows'], ['Open featured dossier', ROUTES.TALENT_REPORT('elena-rodriguez'), 'description']]),
  recruiterCompare: module('recruiter', 'Decision intelligence', 'Compare evidence, not just resumes.', 'compare_arrows',
    'Evaluate candidates across verified capability, consistency, delivery record, and role fit from one decision-ready view.',
    [['Comparison axes', '06'], ['Candidate slots', '04'], ['Evidence freshness', 'Live']],
    ['Choose finalists from your active shortlist.', 'Weight the signals that matter for this role.', 'Open the evidence trail before recording a decision.'],
    [['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['Open pipeline', ROUTES.RECRUITER_PIPELINE, 'account_tree'], ['View Elena’s dossier', ROUTES.TALENT_REPORT('elena-rodriguez'), 'description']]),
  verification: module('candidate', 'Trust layer', 'Evidence that holds up under review.', 'verified_user',
    'Every profile signal is linked to attributable work, credentials, and outcomes so confidence is easy to inspect.',
    [['Signals checked', '40+'], ['Integrity confidence', '98%'], ['Verification status', 'Active']],
    ['Collect source-backed evidence from connected accounts.', 'Map every signal to a consistent skill framework.', 'Expose an explainable trail for candidate and recruiter review.'],
    [['Build your identity', ROUTES.CANDIDATE_PROFILE, 'fingerprint'], ['Explore talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['View featured dossier', ROUTES.TALENT_REPORT('elena-rodriguez'), 'description']]),
  matching: module('recruiter', 'Role fit', 'Find the signal behind the match.', 'hub',
    'Bring skills, project evidence, delivery history, and growth potential together to create a defensible fit score.',
    [['Signals considered', '08'], ['Top match', '94%'], ['Role readiness', 'High']],
    ['Describe the role in your own words.', 'Prioritise the evidence that predicts success.', 'Review ranked profiles with transparent match context.'],
    [['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['Compare candidates', ROUTES.RECRUITER_COMPARE, 'compare_arrows'], ['Review hiring pipeline', ROUTES.RECRUITER_PIPELINE, 'account_tree']]),
  analytics: module('recruiter', 'Hiring intelligence', 'See where your hiring signal is strongest.', 'query_stats',
    'Turn your talent funnel into a clear operating view of quality, velocity, verified skills, and decision confidence.',
    [['Talent pool', '1.2K'], ['Average profile confidence', '89%'], ['Shortlist velocity', '+18%']],
    ['Track your strongest sources of verified talent.', 'Identify bottlenecks between discovery and interview.', 'Use evidence coverage to improve hiring confidence.'],
    [['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['Open pipeline', ROUTES.RECRUITER_PIPELINE, 'account_tree'], ['Explore matching', ROUTES.MATCHING, 'hub']]),
  interviewReport: module('candidate', 'Interview intelligence', 'Understand the story behind your performance.', 'fact_check',
    'Review a structured summary of technical depth, communication, and problem-solving after a practice interview.',
    [['Technical depth', '91'], ['Communication', '88'], ['Problem solving', '93']],
    ['Review category-level feedback and supporting moments.', 'Turn your strongest answers into portfolio evidence.', 'Use targeted recommendations before your next interview.'],
    [['Start interview practice', ROUTES.INTERVIEW, 'record_voice_over'], ['Open talent cockpit', ROUTES.CANDIDATE_OVERVIEW, 'space_dashboard'], ['View career roadmap', ROUTES.CANDIDATE_ROADMAP, 'route']]),
};

Object.assign(productModules, {
  resumeBuilder: module('candidate', 'Career assets', 'Turn verified work into an interview-ready story.', 'description',
    'Create a polished, evidence-led resume and portfolio outline from the strongest work in your TalentIQ identity.',
    [['Evidence selected', '12'], ['Resume readiness', '94%'], ['Portfolio projects', '04']],
    ['Choose the achievements and skill evidence most relevant to your target role.', 'Generate an ATS-friendly profile narrative from verified work.', 'Export a role-specific resume and portfolio outline.'],
    [['View talent identity', ROUTES.CANDIDATE_PROFILE, 'fingerprint'], ['Explore job matches', ROUTES.CANDIDATE_JOBS, 'work'], ['Open career roadmap', ROUTES.CANDIDATE_ROADMAP, 'route']]),
  jobRecommendations: module('candidate', 'Opportunity intelligence', 'Opportunities that match your demonstrated strengths.', 'work',
    'See role recommendations shaped by verified skills, project depth, technical consistency, and growth trajectory.',
    [['Matched roles', '18'], ['Best role fit', '94%'], ['New this week', '06']],
    ['Review the skills and evidence most relevant to each role.', 'Prioritise opportunities where your technical proof is strongest.', 'Use the career roadmap to close the highest-impact gaps.'],
    [['Build a resume', ROUTES.CANDIDATE_RESUME, 'description'], ['Open talent cockpit', ROUTES.CANDIDATE_OVERVIEW, 'space_dashboard'], ['View career roadmap', ROUTES.CANDIDATE_ROADMAP, 'route']]),
  teamContributions: module('candidate', 'Collaboration evidence', 'Show the contribution behind the commit history.', 'groups',
    'Surface the work that demonstrates ownership, collaboration, review quality, and consistent delivery across technical projects.',
    [['Contributions tracked', '248'], ['Pull requests', '36'], ['Collaboration score', '90']],
    ['Connect repositories and project workspaces.', 'Review commits, pull requests, and delivery patterns in context.', 'Attach collaboration evidence to your trusted identity.'],
    [['Open talent cockpit', ROUTES.CANDIDATE_OVERVIEW, 'space_dashboard'], ['Build your identity', ROUTES.CANDIDATE_PROFILE, 'fingerprint'], ['Practice interview', ROUTES.INTERVIEW, 'record_voice_over']]),
  presentations: module('candidate', 'Presentation intelligence', 'Make every project pitch easier to evaluate.', 'slideshow',
    'Review a pitch deck through innovation, technical feasibility, clarity, business potential, and presentation-quality signals.',
    [['Pitch quality', '89'], ['Technical feasibility', '92'], ['Innovation signal', '90']],
    ['Upload a project presentation or pitch deck.', 'Review the structured signals behind its pitch assessment.', 'Use focused recommendations to strengthen the next presentation.'],
    [['View talent identity', ROUTES.CANDIDATE_PROFILE, 'fingerprint'], ['Track hackathon work', ROUTES.HACKATHONS, 'emoji_events'], ['Open featured dossier', ROUTES.TALENT_REPORT('elena-rodriguez'), 'description']]),
  hackathons: module('recruiter', 'Hackathon-to-hiring', 'Turn exceptional hackathon work into hiring momentum.', 'emoji_events',
    'Identify high-performing teams and projects through participation, outcomes, innovation, and delivery evidence.',
    [['Active events', '08'], ['Top performers', '36'], ['Projects reviewed', '142']],
    ['Review participant performance and project outcomes.', 'Compare innovative work with verified technical signals.', 'Move standout builders into a recruiter shortlist.'],
    [['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['Open pipeline', ROUTES.RECRUITER_PIPELINE, 'account_tree'], ['Explore matching', ROUTES.MATCHING, 'hub']]),
  trustFraud: module('recruiter', 'Trust and risk', 'Make confidence visible before a hiring decision.', 'shield',
    'Consolidate certificate, project, resume, and duplicate-profile checks into a clear authenticity and risk view.',
    [['Authenticity confidence', '96%'], ['Signals reviewed', '40+'], ['Risk status', 'Low']],
    ['Trace each important claim back to its supporting evidence.', 'Highlight inconsistencies for careful recruiter review.', 'Include confidence context with every candidate decision.'],
    [['Open verification', ROUTES.VERIFICATION, 'verified_user'], ['Search talent', ROUTES.RECRUITER_SEARCH, 'travel_explore'], ['View featured dossier', ROUTES.TALENT_REPORT('elena-rodriguez'), 'description']]),
});
